# Generated by Django 4.2.1 on 2024-11-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_pt',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title_pt',
        ),
    ]
