# Generated by Django 4.2.1 on 2025-02-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_category_title_en_remove_category_title_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/video'),
        ),
    ]
