# Generated by Django 4.2.1 on 2026-02-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
