# Generated by Django 4.2.1 on 2025-03-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0043_alter_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
